---
# tasks file for roles/ansible-role-adauth

# actual configuration for NSS and PAM should be in another module to allow flexibility with other authentication methods

- include_tasks: redhat.yml
  when: adauth_enabled and ansible_os_family == "RedHat"

